type ConfirmationProps = {
          onContinue: () => void;
          };

          export default function Confirmation({
            onContinue,
            }: ConfirmationProps) {
              return (
                  <div
                        style={{
                                minHeight: "100vh",
                                        background: "#f4f7fb",
                                                display: "flex",
                                                        justifyContent: "center",
                                                                alignItems: "center",
                                                                        padding: "20px",
                                                                                boxSizing: "border-box",
                                                                                      }}
                                                                                          >
                                                                                                <div
                                                                                                        style={{
                                                                                                                  width: "100%",
                                                                                                                            maxWidth: "420px",
                                                                                                                                      background: "white",
                                                                                                                                                padding: "35px 30px",
                                                                                                                                                          borderRadius: "16px",
                                                                                                                                                                    boxShadow:
                                                                                                                                                                                "0 4px 20px rgba(0,0,0,0.1)",
                                                                                                                                                                                          boxSizing: "border-box",
                                                                                                                                                                                                    textAlign: "center",
                                                                                                                                                                                                            }}
                                                                                                                                                                                                                  >
                                                                                                                                                                                                                          {/* Success icon */}
                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                        width: "80px",
                                                                                                                                                                                                                                                                    height: "80px",
                                                                                                                                                                                                                                                                                margin: "0 auto 20px",
                                                                                                                                                                                                                                                                                            borderRadius: "50%",
                                                                                                                                                                                                                                                                                                        background: "#dcfce7",
                                                                                                                                                                                                                                                                                                                    display: "flex",
                                                                                                                                                                                                                                                                                                                                justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                            alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                        fontSize: "42px",
                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                    ✅
                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                    <h1
                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#1565c0",
                                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Email Verified!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#555",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lineHeight: "1.6",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Your email address has been
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  successfully verified.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#666",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lineHeight: "1.6",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "25px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Your MingleMart account is ready.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  You can now connect with people,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            buy, sell, and meet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={onContinue}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    background: "#1565c0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Continue to MingleMart
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "#888",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: "13px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Connect • Buy • Sell • Meet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
