type Item = {
    title: string;
      category: string;
        price: string;
          location: string;
            description: string;
              image: string;
              };

              type ItemDetailsProps = {
                item: Item;
                  onBack: () => void;
                    onContactSeller: () => void;
                    };

                    export default function ItemDetails({
                      item,
                        onBack,
                          onContactSeller,
                          }: ItemDetailsProps) {
                            return (
                                <div
                                      style={{
                                              minHeight: "100vh",
                                                      background: "#f4f7fb",
                                                              padding: "20px",
                                                                    }}
                                                                        >
                                                                              <div
                                                                                      style={{
                                                                                                maxWidth: "600px",
                                                                                                          margin: "0 auto",
                                                                                                                    background: "white",
                                                                                                                              padding: "20px",
                                                                                                                                        borderRadius: "15px",
                                                                                                                                                }}
                                                                                                                                                      >
                                                                                                                                                              <button
                                                                                                                                                                        onClick={onBack}
                                                                                                                                                                                  style={{
                                                                                                                                                                                              padding: "10px 15px",
                                                                                                                                                                                                          border: "none",
                                                                                                                                                                                                                      borderRadius: "8px",
                                                                                                                                                                                                                                  cursor: "pointer",
                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                              ← Back
                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                              {item.image && (
                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                    src={item.image}
                                                                                                                                                                                                                                                                                                                alt={item.title}
                                                                                                                                                                                                                                                                                                                            style={{
                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                        maxHeight: "350px",
                                                                                                                                                                                                                                                                                                                                                                      objectFit: "contain",
                                                                                                                                                                                                                                                                                                                                                                                    marginTop: "15px",
                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                        <h1>{item.title}</h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 style={{ color: "#1565c0" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          KSh {item.price}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <strong>Category:</strong> {item.category}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <strong>📍 Location:</strong> {item.location}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>Description:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {item.description || "No description provided."}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* CHAT BUTTON */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={onContactSeller}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              background: "#1565c0",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: "18px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: "bold",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  💬 Contact Seller
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
