import { useState } from "react";
import { signInWithEmailAndPassword } from "firebase/auth";
import { auth } from "./firebase";

type LoginProps = {
  onLoggedIn: () => void;
    onCreateAccount: () => void;
    };

    export default function Login({
      onLoggedIn,
        onCreateAccount,
        }: LoginProps) {
          const [email, setEmail] = useState("");
            const [password, setPassword] = useState("");
              const [error, setError] = useState("");
                const [loading, setLoading] = useState(false);

                  const handleLogin = async () => {
                      setError("");

                          if (!email.trim() || !password) {
                                setError("Please enter your email and password.");
                                      return;
                                          }

                                              setLoading(true);

                                                  try {
                                                        const result = await signInWithEmailAndPassword(
                                                                auth,
                                                                        email.trim(),
                                                                                password
                                                                                      );

                                                                                            // Require email verification before entering MingleMart.
                                                                                                  if (!result.user.emailVerified) {
                                                                                                          setError("Please verify your email before logging in.");
                                                                                                                  return;
                                                                                                                        }

                                                                                                                              onLoggedIn();
                                                                                                                                  } catch (err) {
                                                                                                                                        console.error("Login error:", err);
                                                                                                                                              setError("Login failed. Check your email and password.");
                                                                                                                                                  } finally {
                                                                                                                                                        setLoading(false);
                                                                                                                                                            }
                                                                                                                                                              };

                                                                                                                                                                return (
                                                                                                                                                                    <div
                                                                                                                                                                          style={{
                                                                                                                                                                                  maxWidth: "400px",
                                                                                                                                                                                          margin: "40px auto",
                                                                                                                                                                                                  padding: "24px",
                                                                                                                                                                                                          fontFamily: "Arial, sans-serif",
                                                                                                                                                                                                                  textAlign: "center",
                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                  <h1 style={{ color: "#16803c" }}>MingleMart</h1>

                                                                                                                                                                                                                                        <p>Connect • Buy • Sell • Meet</p>

                                                                                                                                                                                                                                              <h2>Welcome Back</h2>

                                                                                                                                                                                                                                                    <form
                                                                                                                                                                                                                                                            onSubmit={(event) => {
                                                                                                                                                                                                                                                                      event.preventDefault();
                                                                                                                                                                                                                                                                                void handleLogin();
                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                type="email"
                                                                                                                                                                                                                                                                                                                          placeholder="Email address"
                                                                                                                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                                                                                                              onChange={(event) => setEmail(event.target.value)}
                                                                                                                                                                                                                                                                                                                                                        autoComplete="email"
                                                                                                                                                                                                                                                                                                                                                                  required
                                                                                                                                                                                                                                                                                                                                                                            style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                          value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(event) => setPassword(event.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                              autoComplete="current-password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={inputStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style={{ color: "red", fontSize: "14px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={buttonStyle}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? "Logging in..." : "Login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ marginTop: "20px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Don't have an account?
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={onCreateAccount}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...buttonStyle,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      backgroundColor: "#ffffff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: "#16803c",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border: "1px solid #16803c",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Create Account
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const inputStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: "block",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  boxSizing: "border-box",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      marginBottom: "14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid #cccccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const buttonStyle: React.CSSProperties = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: "#16803c",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: "16px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };